name: pressing_managerapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  http: ^0.13.5
  file_picker: ^5.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  search_map_place_updated: ^0.0.4
  intl: ^0.18.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_secure_storage: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
